import 'package:flutter/material.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedEllipse4Widget4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedEllipse1Widget4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedEstadosypublicacionesWidget6.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedPedroPrezWidget4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedEllipse7Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedEllipse8Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle4Widget6.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle19Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/Generated22denoviembredde2021Widget4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedAadeatupublicacinWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedPedroPrezWidget5.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedPublicarWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle20Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle21Widget6.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedQuestaspensandoWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiospublicacinwidget/generated/GeneratedRectangle10Widget.dart';

/* Frame estadosPropiosPublicación
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstadosPropiosPublicacinWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle1Widget7(),
              ),
              Positioned(
                left: 217.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedEllipse1Widget4(),
              ),
              Positioned(
                left: 266.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 18.0,
                child: GeneratedPedroPrezWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 169.0,
                child: GeneratedRectangle4Widget6(),
              ),
              Positioned(
                left: 37.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 50.0,
                child: GeneratedEllipse4Widget4(),
              ),
              Positioned(
                left: 103.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 19.0,
                child: GeneratedEstadosypublicacionesWidget6(),
              ),
              Positioned(
                left: 103.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 17.0,
                child: Generated22denoviembredde2021Widget4(),
              ),
              Positioned(
                left: 32.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 58.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali4(),
              ),
              Positioned(
                left: 12.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse7Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 299.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 31.0,
                child: GeneratedQuestaspensandoWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedEllipse8Widget3(),
              ),
              Positioned(
                left: 74.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 20.0,
                child: GeneratedPedroPrezWidget5(),
              ),
              Positioned(
                left: 25.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 40.0,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 20.0,
                child: GeneratedAadeatupublicacinWidget(),
              ),
              Positioned(
                left: 250.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 32.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 373.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 37.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 26.0,
                child: GeneratedPublicarWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedRectangle19Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle20Widget3(),
              ),
              Positioned(
                left: 129.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle21Widget6(),
              ),
              Positioned(
                left: 257.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle22Widget2(),
              )
            ]),
      ),
    ));
  }
}
