import 'package:flutter/material.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedEllipse8Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedPedroPrezWidget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle17Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedFridaKahloWidget.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedNaturalezamuertavivalavidaWidget.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedPaisajemediterrneoWidget.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedEllipse5Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/Generated5Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/Generated10Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedMegustaWidget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedLine3Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedPabloPicassoWidget.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpiezasdeartesserviciowebwidget/generated/GeneratedRectangle1Widget5.dart';

/* Frame piezasDeArtesServicioWEB
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPiezasDeArtesServicioWEBWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 217.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 266.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 18.0,
                child: GeneratedPedroPrezWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 251.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 273.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 72.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedMegustaWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 20.0,
                child: GeneratedPabloPicassoWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 17.0,
                child: GeneratedPaisajemediterrneoWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 20.0,
                child: GeneratedFridaKahloWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 17.0,
                child: GeneratedNaturalezamuertavivalavidaWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 299.0016784667969,
                height: 1.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 32.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 299.0016784667969,
                height: 1.0,
                child: GeneratedLine3Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 37.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 22.0,
                child: GeneratedEllipse3Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 22.0,
                child: GeneratedEllipse5Widget2(),
              ),
              Positioned(
                left: 72.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 23.0,
                child: Generated5Widget2(),
              ),
              Positioned(
                left: 71.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 23.0,
                child: Generated10Widget2(),
              ),
              Positioned(
                left: 11.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse8Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 123.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 107.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle16Widget2(),
              ),
              Positioned(
                left: 129.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle17Widget2(),
              ),
              Positioned(
                left: 257.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle18Widget2(),
              )
            ]),
      ),
    ));
  }
}
