import 'package:flutter/material.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle5Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle4Widget5.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedPedroPrezWidget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEllipse4Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/Generated5Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedMegustaWidget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedCrearpublicacinWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle21Widget5.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEstadosypublicacionesWidget5.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEllipse4Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEstadosypublicacionesWidget4.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/Generated22denoviembredde2021Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedEllipse5Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/Generated22denoviembredde2021Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadospropiosperfilwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali3.dart';

/* Frame estadosPropiosPerfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstadosPropiosPerfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle1Widget6(),
              ),
              Positioned(
                left: 217.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedEllipse1Widget3(),
              ),
              Positioned(
                left: 266.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 18.0,
                child: GeneratedPedroPrezWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 169.0,
                child: GeneratedRectangle4Widget4(),
              ),
              Positioned(
                left: 22.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 85.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 50.0,
                child: GeneratedEllipse4Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 19.0,
                child: GeneratedEstadosypublicacionesWidget4(),
              ),
              Positioned(
                left: 103.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 17.0,
                child: Generated22denoviembredde2021Widget2(),
              ),
              Positioned(
                left: 32.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 58.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali2(),
              ),
              Positioned(
                left: 94.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 38.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 23.0,
                child: GeneratedCrearpublicacinWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 230.0,
                child: GeneratedRectangle4Widget5(),
              ),
              Positioned(
                left: 74.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedMegustaWidget3(),
              ),
              Positioned(
                left: 39.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedEllipse4Widget3(),
              ),
              Positioned(
                left: 105.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 20.0,
                child: GeneratedEstadosypublicacionesWidget5(),
              ),
              Positioned(
                left: 105.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 17.0,
                child: Generated22denoviembredde2021Widget3(),
              ),
              Positioned(
                left: 34.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali3(),
              ),
              Positioned(
                left: 39.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedRectangle5Widget3(),
              ),
              Positioned(
                left: 39.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 22.0,
                child: GeneratedEllipse5Widget3(),
              ),
              Positioned(
                left: 74.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 23.0,
                child: Generated5Widget3(),
              ),
              Positioned(
                left: 34.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 299.0016784667969,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedRectangle19Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle20Widget2(),
              ),
              Positioned(
                left: 129.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle21Widget5(),
              ),
              Positioned(
                left: 257.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle22Widget1(),
              )
            ]),
      ),
    ));
  }
}
