import 'package:flutter/material.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEstadosypublicacionesWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/Generated22denoviembredde2021Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEstadosypublicacionesWidget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedMegustaWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/Generated5Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/Generated10Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/Generated21denoviembredde2021Widget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedPedroPrezWidget.dart';
import 'package:flutterapp/redsocialapp/generatedestadosotrosusuarioswidget/generated/GeneratedRectangle16Widget1.dart';

/* Frame estadosOtrosUsuarios
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstadosOtrosUsuariosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 217.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 266.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 18.0,
                child: GeneratedPedroPrezWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 230.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 230.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 72.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 20.0,
                child: GeneratedMegustaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 51.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 20.0,
                child: GeneratedEstadosypublicacionesWidget(),
              ),
              Positioned(
                left: 103.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 20.0,
                child: GeneratedEstadosypublicacionesWidget1(),
              ),
              Positioned(
                left: 103.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 17.0,
                child: Generated22denoviembredde2021Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 17.0,
                child: Generated21denoviembredde2021Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali(),
              ),
              Positioned(
                left: 32.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitmagnaali1(),
              ),
              Positioned(
                left: 32.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 299.0016784667969,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 299.0016784667969,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 299.0016784667969,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 22.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 22.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 23.0,
                child: Generated5Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 23.0,
                child: Generated10Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 129.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 257.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 38.0,
                child: GeneratedRectangle18Widget1(),
              )
            ]),
      ),
    ));
  }
}
