import 'package:flutter/material.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEstadosypublicacionesWidget3.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/Generated21denoviembredde2021Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEllipse8Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEstadosypublicacionesWidget2.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedPedroPrezWidget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/Generated10Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEllipse5Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/Generated5Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedMegustaWidget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/Generated22denoviembredde2021Widget1.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle21Widget4.dart';
import 'package:flutterapp/redsocialapp/generatedpublicacionesotrosusuarioswidget/generated/GeneratedRectangle5Widget1.dart';

/* Frame publicacionesOtrosUsuarios
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPublicacionesOtrosUsuariosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(
          context, '/GeneratedPiezasDeArtesServicioWEBWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 60.0,
                  child: GeneratedRectangle1Widget4(),
                ),
                Positioned(
                  left: 217.0,
                  top: 11.0,
                  right: null,
                  bottom: null,
                  width: 38.0,
                  height: 38.0,
                  child: GeneratedEllipse1Widget1(),
                ),
                Positioned(
                  left: 266.0,
                  top: 22.0,
                  right: null,
                  bottom: null,
                  width: 78.0,
                  height: 18.0,
                  child: GeneratedPedroPrezWidget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 78.0,
                  right: null,
                  bottom: null,
                  width: 327.0,
                  height: 251.0,
                  child: GeneratedRectangle2Widget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 352.0,
                  right: null,
                  bottom: null,
                  width: 327.0,
                  height: 273.0,
                  child: GeneratedRectangle4Widget2(),
                ),
                Positioned(
                  left: 72.0,
                  top: 301.0,
                  right: null,
                  bottom: null,
                  width: 65.0,
                  height: 20.0,
                  child: GeneratedMegustaWidget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 92.0,
                  right: null,
                  bottom: null,
                  width: 51.0,
                  height: 51.0,
                  child: GeneratedEllipse2Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 374.0,
                  right: null,
                  bottom: null,
                  width: 51.0,
                  height: 51.0,
                  child: GeneratedEllipse4Widget1(),
                ),
                Positioned(
                  left: 103.0,
                  top: 105.0,
                  right: null,
                  bottom: null,
                  width: 164.0,
                  height: 20.0,
                  child: GeneratedEstadosypublicacionesWidget2(),
                ),
                Positioned(
                  left: 103.0,
                  top: 378.0,
                  right: null,
                  bottom: null,
                  width: 164.0,
                  height: 20.0,
                  child: GeneratedEstadosypublicacionesWidget3(),
                ),
                Positioned(
                  left: 103.0,
                  top: 124.0,
                  right: null,
                  bottom: null,
                  width: 156.0,
                  height: 17.0,
                  child: Generated22denoviembredde2021Widget1(),
                ),
                Positioned(
                  left: 103.0,
                  top: 397.0,
                  right: null,
                  bottom: null,
                  width: 156.0,
                  height: 17.0,
                  child: Generated21denoviembredde2021Widget1(),
                ),
                Positioned(
                  left: 32.0,
                  top: 285.0,
                  right: null,
                  bottom: null,
                  width: 299.0016784667969,
                  height: 1.0,
                  child: GeneratedLine1Widget1(),
                ),
                Positioned(
                  left: 32.0,
                  top: 579.0,
                  right: null,
                  bottom: null,
                  width: 299.0016784667969,
                  height: 1.0,
                  child: GeneratedLine3Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 290.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 27.0,
                  child: GeneratedRectangle3Widget2(),
                ),
                Positioned(
                  left: 37.0,
                  top: 585.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 27.0,
                  child: GeneratedRectangle5Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 259.0,
                  right: null,
                  bottom: null,
                  width: 27.0,
                  height: 22.0,
                  child: GeneratedEllipse3Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 549.0,
                  right: null,
                  bottom: null,
                  width: 27.0,
                  height: 22.0,
                  child: GeneratedEllipse5Widget1(),
                ),
                Positioned(
                  left: 72.0,
                  top: 261.0,
                  right: null,
                  bottom: null,
                  width: 14.0,
                  height: 23.0,
                  child: Generated5Widget1(),
                ),
                Positioned(
                  left: 71.0,
                  top: 551.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 23.0,
                  child: Generated10Widget1(),
                ),
                Positioned(
                  left: 11.0,
                  top: 3.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 46.0,
                  child: GeneratedEllipse8Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 431.0,
                  right: null,
                  bottom: null,
                  width: 294.0,
                  height: 108.0,
                  child: GeneratedRectangle11Widget(),
                ),
                Positioned(
                  left: 37.0,
                  top: 148.0,
                  right: null,
                  bottom: null,
                  width: 294.0,
                  height: 107.0,
                  child: GeneratedRectangle12Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 594.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 46.0,
                  child: GeneratedRectangle19Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 597.0,
                  right: null,
                  bottom: null,
                  width: 103.0,
                  height: 38.0,
                  child: GeneratedRectangle20Widget1(),
                ),
                Positioned(
                  left: 129.0,
                  top: 598.0,
                  right: null,
                  bottom: null,
                  width: 103.0,
                  height: 38.0,
                  child: GeneratedRectangle21Widget4(),
                ),
                Positioned(
                  left: 257.0,
                  top: 598.0,
                  right: null,
                  bottom: null,
                  width: 103.0,
                  height: 38.0,
                  child: GeneratedRectangle22Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
